### ISSUE TITLE
i18n improvements - Make it easier to translate the plugin

### ISSUE THREAD

**Issue by ramiy** [woocommerce/woocommerce#12079]
## THE ISSUE

With over 4500 translation strings it's very hard to translate WooCommerce to other languages.  Let's fix that!

Many translation strings use wrong i18n functions. I see many `_x()` context function instead of translation comments ([reference](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/he/default?filters%5Bterm%5D=&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bwith_context%5D=yes&filter=Filter&sort%5Bby%5D=original&sort%5Bhow%5D=asc)).

Almost all the the translation strings with `%s` placeholders have no translation comments, I see [only one translation string with translation comments](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/he/default?filters%5Bterm%5D=&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bwith_comment%5D=yes&filter=Filter&sort%5Bby%5D=original&sort%5Bhow%5D=asc). It's very hard to translate strings with `%s` placeholders without knowing what you are trying to translate.

In WordPress core we removed HTML tags from translation strings. The same needs to be done in WooCommerce. In RTL languages it's very hard to translate when you have HTML tags, because they are LTR.
## TODO
- [x] Merge similar translation strings. #12058
- [x] Avoid code concatenation in translation strings, use `sprintf()` with `%s` placeholders. #12078
- [x] Replace wrong `_x()` context function with translation comments. #12156
- [x] Avoid using HTML tags in translation strings. #12166
- [x] Better handling with direction characters like `&larr;` and `&rarr;`. #12177 
- [x] Add translation comments to translation strings with `%s` placeholders. #12219

**Comment by claudiosanches** [comment]
@ramiy thank you very much for your help.

**Comment by ramiy** [comment]
@claudiosanches No problem. I have many more things to fix - RTL, a11y and others...
