### ISSUE TITLE
RTL improvements

### ISSUE THREAD

**Issue by ramiy** [woocommerce/woocommerce#12170]
## THE ISSUE

WooCommerce RTL support is not perfect, many items don't flip as expected and some look broken. Lets fix that!
## TODO
- [ ] Add grunt RTL task to generate CSS files for RTL languages.
- [ ] Fix original CSS files to work well with LRT and RTL views.
- [x] Better handling with direction characters like `&larr;` and `&rarr;`. #12177
- [ ] More to come...

**Comment by mikejolley** [comment]
Closing in favour of #12917
