### ISSUE TITLE
a11y improvements

### ISSUE THREAD

**Issue by ramiy** [woocommerce/woocommerce#12250]
## THE ISSUE

WooCommerce is not the most accessible WordPress plugin. Lets fix that!

## TODO

- [ ] Check label focus with `for` attributes.
- [x] Replace `title` attributes with `aria-label` where needed. #12252
- [x] Accessible tabs with `role` and ARIA tags. #12257 
- [x] Accessible order notes metabox. #12261
- [ ] Add `aria-required="true"` to required fields.
- [ ] Table accessibility.
- [ ] More to come...

**Comment by mikejolley** [comment]
We can close this out and factor into the checkout redesign. If areas need particular attention, let's have dedicated issues logged so the issue is not too wide in scope.
