### ISSUE TITLE
Webhooks CRUD

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#12439]
Currently webhooks uses `shop_webhook` post type and `webhook_delivery` comment type, what is not the ideal, since every time a webhook is triggered a new comment is create.
So we should wrap webhooks into a CRUD and log the deliveries into the new WC_Logger system, and webhooks is a good candidate to be moved to new tables, since there is not too many data to be migrated.

TODO

- [ ] Allow body to be set so it's sent based on the data at the time of the event #15699
- [x] Add variation triggers too #15198
- [x] Log duration to generate webhook data https://github.com/woocommerce/woocommerce/issues/17010

**Comment by mikejolley** [comment]
Todo: Add variation triggers too https://github.com/woocommerce/woocommerce/issues/15198

**Comment by mikejolley** [comment]
Todo: Allow body to be set so it's sent based on the data at the time of the event https://github.com/woocommerce/woocommerce/issues/15699

**Comment by mikejolley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Webhooks CRUD](https://trello.com/c/OCN6YYKm/105-webhooks-crud)

**Comment by mikejolley** [comment]
Investigate; webhooks in table, cron to serve from table (periodically).

**Comment by claudiosanches** [comment]
Note: need to remember `set_user_id()` while creating webhooks on admin.
