### ISSUE TITLE
Stock Reduction Events

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13359]
This issue should take care of:

- [x] Manually adding orders does not reduce stock https://github.com/woocommerce/woocommerce/issues/5117
- [x] Order stock may be reduced twice if the order is paid for again using different gateways https://github.com/woocommerce/woocommerce/issues/13349
- [x] If stock reduction is complete (or done manually) we can disable stock level checks on payment. https://github.com/woocommerce/woocommerce/issues/18399

We need to have more robust stock reduction/increase events and ensure it's only done once.

**Comment by masiorama** [comment]
In my case the order stock is reduced twice also when changing the order status from "Processing" to "Completed".

**Comment by mikejolley** [comment]
Part of https://github.com/woocommerce/woocommerce/issues/16971

**Comment by kellychoffman** [comment]
>  Manually adding orders does not reduce stock #5117

I'm most excited about this. Adding orders through the front end or manually on the admin side should not change how stock is being effected.

**Comment by masiorama** [comment]
The issue was removed from the milestone 3.3.0. What does this mean? When can we expect the fix to be delivered? Thanks in advance.

**Comment by claudiosanches** [comment]
@masiorama this is not a fix, this is a new feature. You can follow our dev blog and our dev chat to know more about our releases: https://woocommerce.wordpress.com/

**Comment by masiorama** [comment]
@claudiosanches I don't understand how it can be treated as 'new feature' as it is clear (at least to me) that there are several bugs as regards to the feature (managing stock) at the current situation. 
Are you saying that we are supposed to edit out stock manually till... when? Thanks!

**Comment by bobteree** [comment]
Agreed with most of this thread. Regardless of whether and order is manually created (think taking an order over the phone) vs a front-end (self-service) type of sale, as soon as payment is made and cleared (i.e. whatever the event is for a self-service order), if the status of an order is set to "Processing", whether automatically or manually, that state should dictate inventory reductions. Perhaps this is an admin setting to automate this for manual orders (kinda ugly). The next question then is what happens if the status is manually changed back to something like "pending payment?" Either the status changes simply need to be a flag or an action or both. But manually reducing stock for manual orders (e.g. taking an order over the phone) is not a solution. This must be automated.

**Comment by masiorama** [comment]
Any updates?

**Comment by mikejolley** [comment]
Unless you see any comments above, no :)

**Comment by rekkitatu** [comment]
Would fixing this issue also help in the situation where the quantity left in stock is only 1, but it's held in a order with a pending payment? This is a quite big problem for us as all the items we are selling are unique and there needs to be about 48 hours period to hold the items in pending orders just to clear out the potential cases where customer hasn't returned from the payment gateway after completing the payment or where there has been other problems with the payment.

**Comment by WPprodigy** [comment]
@rekkitatu This setting already helps solve that problem by cancelling orders: http://cld.wthms.co/bpx6Gh

**Comment by rekkitatu** [comment]
Yes @WPprodigy we have that option in use as it holds the product reserved for the 48 hours in our case. However, while the products are held for the pending orders they can still be added to cart. The notice: "Sorry, we do not have enough "%1$s" in stock to fulfill your order right now. Please try again in %2$d minutes or edit your cart and try again. We apologize for any inconvenience caused." comes only after adding the product to cart. And at least in our use case it would be more convenient for our customers to perhaps have the add to cart button disabled with products that are not available for purchase at that moment or maybe event have those products not shown at all. As we sell unique single quantity items customers typically suppose that everything that has an "add to cart"-button available is theirs to purchase and these problems with the stock availability not being up to date lower the conversion rate and lead to unnecessary confusion with some customers.

As a quick fix I added this to my theme functions.php to prevent adding products to cart if the available quantity is the same as the stock held for the pending orders. I just customized the code from the class-wc-cart.php. It works, but I'm not sure if it scales that well to situations where there are a lot of pending orders and products.

```
add_filter('woocommerce_is_purchasable', 'custom_check_cart_item_stock', 10, 2);
function custom_check_cart_item_stock($is_purchasable, $product) {
	global $wpdb;
	if ( get_option( 'woocommerce_hold_stock_minutes' ) > 0 && ! $product->backorders_allowed() ) {
		$order_id   = isset( WC()->session->order_awaiting_payment ) ? absint( WC()->session->order_awaiting_payment ) : 0;
		$held_stock = $wpdb->get_var(
			$wpdb->prepare( "
				SELECT SUM( order_item_meta.meta_value ) AS held_qty
				FROM {$wpdb->posts} AS posts
				LEFT JOIN {$wpdb->prefix}woocommerce_order_items as order_items ON posts.ID = order_items.order_id
				LEFT JOIN {$wpdb->prefix}woocommerce_order_itemmeta as order_item_meta ON order_items.order_item_id = order_item_meta.order_item_id
				LEFT JOIN {$wpdb->prefix}woocommerce_order_itemmeta as order_item_meta2 ON order_items.order_item_id = order_item_meta2.order_item_id
				WHERE 	order_item_meta.meta_key   = '_qty'
				AND 	order_item_meta2.meta_key  = %s AND order_item_meta2.meta_value  = %d
				AND 	posts.post_type            IN ( '" . implode( "','", wc_get_order_types() ) . "' )
				AND 	posts.post_status          = 'wc-pending'
				AND		posts.ID                   != %d;",
				'variation' === get_post_type( $product->get_stock_managed_by_id() ) ? '_variation_id' : '_product_id',
				$product->get_stock_managed_by_id(),
				$order_id
			)
		);
		if ( $product->get_stock_quantity() <= ( $held_stock ) ) {
			$is_purchasable = false;
		}
	}
	return $is_purchasable;
}
```

**Comment by amjad** [comment]
Does this also take care of stock adjustment for orders created via the REST API?

**Comment by PaulKaan** [comment]
When placing manual orders, individual inventory settings for products are over ruled without notification

When we place a manual order, is it possible to reconcile with product inventory management settings.  The order quantity does not recognise the individual product inventory settings so even if a product is set to manage inventory, stock quantity is set and allow backorders is set to do not allow we can over order. At minimum it would be good to display the inventor status for "Manage Stock", "Stock Quantity" and "Allow Backorders" for a product when placing a manual order.

**Comment by PaulKaan** [comment]
@rekkitatu This plugin by @claudiosanches address the problem partly. If it was set to reduce stock when status was pending payment then one of your and my problem would be solved. Currently it reduces stock for manual orders when the order status is changed to either processing or complete and returns it on cancelled. https://github.com/claudiosanches/reduce-stock-of-manual-orders-for-woocommerce
