### ISSUE TITLE
Ensure no updated template versions were missed with 3.0

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#14207]
- [x] view-order.php https://github.com/woocommerce/woocommerce/issues/14183
- [x] form-shipping.php https://github.com/woocommerce/woocommerce/issues/14178
- [x] content-single-product.php https://github.com/woocommerce/woocommerce/issues/14133
- [x] Audited all others
