### ISSUE TITLE
REST API v3

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#15235]
- [ ] Add v3 directory from v2
- [ ] Merge https://github.com/woocommerce/woocommerce/pull/15216
- [ ] Merge https://github.com/woocommerce/woocommerce/pull/15162
- [ ] Fix https://github.com/woocommerce/woocommerce/issues/15215
- [ ] Add v3 as default for webhooks
- [ ] Update documentation

@claudiosanches

**Comment by jasomdotnet** [comment]
add ability to set customer IP address and customer Useragent over the REST API. Now it is read-only.

**Comment by justinshreve** [comment]
I've updated #15216 which handles removing the `visible` property from the variations endpoint, and adds `status`.

**Comment by mikejolley** [comment]
Looks like we don't need to track this issue since we're going with a feature plugin + branch instead 👍
