### ISSUE TITLE
Discount calculation API

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#15498]
Revisiting https://github.com/woocommerce/woocommerce/pull/12006

- Create a class which can take a cart/group of items and apply coupon codes/get discounts back
- Make use of this class in the frontend cart to keep calculations in one place
- Make use of this class in admin and allow coupons to be applied to existing orders

http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/3867647-ability-to-apply-coupons-manually-when-manually-ad

TODO:

- [x] Test against popular coupon extensions - suggestions: smart coupons, woo deposits and account funds
- [ ] Close ideas board item once merged
- [x] Dev blog post showing how it can be used in admin

**Comment by claudiosanches** [comment]
And this can be used in the REST API to apply discounts as well.

**Comment by mikejolley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Discount Calculation API](https://trello.com/c/a4trRLUq/96-discount-calculation-api)

**Comment by pelmered** [comment]
@mikejolley You must stop linking to issues on private Trello boards, or make the board publicly readable. I have seen this on a lot of issues lately and it's not a good practice for open source projects in my opinion.

**Comment by mikejolley** [comment]
@pelmered it's automated. It will be made public when I'm happy to share it.

**Comment by pelmered** [comment]
Ok, sounds good 👍

**Comment by claudiosanches** [comment]
@pelmered just follow our dev chat, we are talking about it on the last month, about a public roadmap outside GitHub, and we are testing how this will go. Since you like open source and good practices, you should follow our dev chat.
