### ISSUE TITLE
Incorrect override instructions in review-meta.php

### ISSUE THREAD

**Issue by andrebalza** [woocommerce/woocommerce#15860]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1. Open woocommerce/templates/single-product/review-meta.php
2. Follow the instructions l:5 to override review-meta.php
`This template can be overridden by copying it to yourtheme/woocommerce/content-product.php.`
3. Edit overridden template

## Expected behavior and actual behavior

The wrong template part on single product has been overridden: 
content-product instead of review-meta.
The correct override instructions should be provided. 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently
