### ISSUE TITLE
Updating an order changes hidden meta data making it invalid (v3.1)

### ISSUE THREAD

**Issue by code937** [woocommerce/woocommerce#15868]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add a hidden field to an order item that contains JSON. (important the type of data as it contains characters which could be escaped)
2. View that JSON data within the order using woocommerce order page (It is currently correct as per new order).
3. Press the update button on an order (without changing anything - or by simply updating the status).
4. Check the custom hidden meta data which will now contain back slashes and will no longer be valid json therefore breaking any further usage of it.

## Expected behavior and actual behavior

It should not change any data within this field as per previous version.

## Environment

Not relevent

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

This is related to a recent fix located here: https://github.com/woocommerce/woocommerce/issues/15808

**Comment by Spreeuw** [comment]
@mikejolley I have seen several sites with this very same issue and infintely double escaped \\ -> \\\\ -> \\\\\\\\ etc. etc. data. These orders ran out of memory on 512M. Will there be a fix for this corrupted data too? When can we expect the release?

**Comment by Spreeuw** [comment]
@mikejolley I don't understand how such a serious bug that **corrupts orders** isn't fixed with a hotfix release even after 11 days!!!
Here's a tentative script that will loop over 3.1.0 orders and strip all the 'infinite' encoding corrupting orders, note that if you do not apply the 3.1.1 patches you will still have the same issue.

BACKUP YOUR DATA BEFORE USING!
I have added options for either removing all escaping or replace all double escapes with a single escape,  and optionally encoding special characters to avoid escaping.
`
add_action( 'init', 'woocommerce_31_fix_escaping' );
function woocommerce_31_fix_escaping() {
    if (!isset($_GET['woocommerce_31_fix_escaping'])) {
        return;
    }

    // get all order ids for WC3.1.0 orders
    $args = array(
        'return'        => 'ids',
        'type'          => 'shop_order',
        'limit'         => -1,
        'version'       => '3.1.0',
    );
    $fix_orders = wc_get_orders( $args );

    // loop over each order and fix meta data if it contains multiple backslashes
    $messages = array();
    foreach ($fix_orders as $fix_order_id) {
        $all_meta = get_post_meta( $fix_order_id );
        foreach ($all_meta as $meta_key => $meta_values) {
            if (is_array($meta_values)) {
                // we assume only single meta values
                $meta_value = $meta_values[0];
                // check if we have more than four backslashes (=8 when escaped in PHP :o)
                if (strpos($meta_value, "\\\\\\\\") !== false) {
                    // OPTION 1: remove multiple escaping (double or higher) entirely
                    $meta_value = str_replace("\\\\", "", $meta_value);
                    // OPTION 2.1: replace with single backslash
                    // $meta_value = preg_replace("/\\\\+/", "\\", $meta_value);
                    // OPTIONAL 2.2: Convert backslash (AND OTHER SPECIAL CHARACTERS!) to html entities
                    // $meta_value = htmlspecialchars( $meta_value, ENT_QUOTES );

                    // save fixed meta_value
                    update_post_meta( $fix_order_id, $meta_key, $meta_value );
                    // save message
                    $messages[] = "Fixed escaping for {$meta_key} in order $fix_order_id";
                }
            }
        }
    }

    wp_die(implode("<br>", $messages));
}
`

**Comment by mikejolley** [comment]
@Spreeuw core orders don't use the CRUD meta setting methods, so it only affects custom functionality. There will be a fix release later today.

**Comment by Spreeuw** [comment]
yes it only affects custom functionality, but the corruption of fields is done by WooCommerce, even when the meta is added with `$order->update_meta_data()`. The WooCommerce methods change/corrupt this data and the external plugins have no control over it. If you change/manage data from other plugins you should take responsibility for it too.

**Comment by mikejolley** [comment]
As I said, the fix release is due out today so I don't think there is anything else to discuss here.

**Comment by Spreeuw** [comment]
The fix 7211821f815d7ba0cfa159dbd87440d1b5e03b6f doesn't fix existing orders, people will still need a script to fix already corrupted orders. I have had reports of people that couldn't open certain orders anymore because they had custom fields that were escaped infinitely/exponentially. With json data (not mine!) in custom fields, this became too large for the system to handle. Order details page didn't show anything, saving didn't work, etc.

**Comment by mikejolley** [comment]
In which case code like the above may be needed, but from what I've seen in support this has been rare in occurrence, and using code like above would be dangerous in the general release (unwanted changes, timeouts etc).
