### ISSUE TITLE
WooCommerce Export meta data

### ISSUE THREAD

**Issue by tgaguy** [woocommerce/woocommerce#15920]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. On the Product Page, Click EXPORT
2. Select certain columns to be exported (dont leave blank)
3. tick Export custom meta data

## Expected behavior and actual behavior

When I follow those steps, I see...

Meta data is not exported

I was expecting...
to see meta data exported (same as when columns field is left blank)

## Environment

<details>
### WordPress Environment ###

Home URL: http://homestory.co.nz
Site URL: http://homestory.co.nz
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_NZ

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_d4h7zfcmm3_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (48) ###

404page - your smart custom 404 error page: by Peter Raschendorfer – 2.5
Add From Server: by Dion Hulse – 3.3.3
Code Snippets: by Shea Bunge – 2.8.6
Under Construction / Maintenance Mode From Acurax: by Acurax – 2.5.3
Contact Widgets: by GoDaddy – 1.4.1
Duplicator: by Snap Creek – 1.2.8
Export User Data: by Q Studio – 1.3.1
File Manager: by  – 4.1.6
Hide Related Products in WooCommerce: by Basit Ansari – 1.0
Page Builder: Live Composer - drag and drop website builder (visual front end site editor): by Live Composer Team – 1.3.1
Ninja Forms: by The WP Ninjas – 3.1.6
Product CSV Import Export (BASIC): by XAdapter – 1.3.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Say What?: by Lee Willis – 1.9.1
Search Engine Visibility: by GoDaddy – 0.5
Storefront Pro (Premium): by pootlepress – 4.4.0
Storefront Pro Skins: by pootlepress – 0.5.0
Storefront Product Pagination: by WooThemes – 1.2.1
Storefront Product Sharing: by WooThemes – 1.0.4
Title Toggle for Storefront Theme: by Wooassist – 1.2.3
Theme Customisations: by WooThemes – 1.0.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.4

User Switching: by John Blackbourn – 1.0.9
Who Hit The Page - Hit Counter: by mahlamusa – 1.4.5
WooCommerce Extended Coupon Features: by Soft79 – 2.5.1
WooCommerce - Backorders Report: by Filament Studios – 1.0.1
WooCommerce Cart Tab: by jameskoster – 1.1.1
WooCommerce - Store Exporter: by Visser Labs – 1.9.1.1
WooCommerce Print Order List: by Ewout Fernhout – 1.5.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.6
WooCommerce PDF Invoices & Packing Slips Professional: by Ewout Fernhout – 1.5.2
WooCommerce PDF Invoices & Packing Slips Premium Templates: by Ewout Fernhout – 2.3.3
WooCommerce Product Archive Customiser: by jameskoster – 1.0.5
WooCommerce Product Sort and Display LITE: by a3rev Software – 1.8.0
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.2
WooCommerce Sequential Order Numbers: by SkyVerge – 1.8.1
WooCommerce Stock Manager: by Vladislav Musílek – 1.1.5
WooCommerce - Store Toolkit: by Visser Labs – 1.7.4
WooCommerce Wholesale Lead Capture: by Rymera Web Co – 1.6.11
WooCommerce Wholesale Order Form: by Rymera Web Co – 1.7.3
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.14.8
WooCommerce Wholesale Prices: by Rymera Web Co – 1.4.5
WooCommerce Xero Integration: by WooCommerce – 1.7.9
WooCommerce: by Automattic – 3.1.0
WordPress Importer: by wordpressdotorg – 0.6.3
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WP101 Video Tutorials: by WP101Plugin.com – 0.3
WP Overnight Sidekick: by Jeremiah Prummer – 1.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
hidden (hidden)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
visible (visible)

### WC Pages ###

Shop base: #1079 - /retail-page/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Templates ###

thumbnail: 
medium: 
medium_large: 
large: 
shop_thumbnail: 
shop_catalog: 
shop_single: 
</details>

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
Just came here to report this 😀

Can confirm that once custom export columns are selected, the `Export custom meta?` option does nothing.

**Comment by WPprodigy** [comment]
I'm not sure if this is the desired effect (if it is, we should hide the checkbox after custom columns are selected).

But if it's not, this is why it's happening: https://github.com/woocommerce/woocommerce/blob/c38d02b62bcdadeb72ffc571a79f0249a29b3b04/includes/export/class-wc-product-csv-exporter.php#L149

Specifically:

```
|| ! $this->is_column_exporting( $column_id )
```

**Comment by WPprodigy** [comment]
If this is the expected result, we should hide the checkbox with JS after specific columns are selected. And there should be a `all custom meta` option in in the 'Which columns should be exported?' select - that way you could do things like export just ID, Name, and custom meta.

If this isn't the expected result, then the problem is here: https://github.com/woocommerce/woocommerce/blob/efaf9293667c6ede632c1bf0213b2e1a0eb30745/includes/export/abstract-wc-csv-exporter.php#L125-L129

**Comment by tgaguy** [comment]
I need to have meta data as well as specific columns as It has meta data as wholesale prices data as well as prices defined in specific columns
