### ISSUE TITLE
Add PayPal Transaction Fees with a sanitized meta key

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#16084]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Expected behavior and actual behavior

PayPal fees [are stored as order meta](https://github.com/woocommerce/woocommerce/blob/dec792b731dbbea6d34aa3ddcd6a3bf05bf43077/includes/gateways/paypal/includes/class-wc-gateway-paypal-pdt-handler.php#L106) for PP standard transactions, which could allow them to be used by third parties. However, while trying to use this data in reports via Cost of Goods, we've found that `WC_Admin_Report::get_order_report_data()` can't use a meta key with a space in its name.

We considered the `woocommerce_reports_get_order_report_query` filter to adjust the query with a string replace, but it felt cleaner to have WC store this meta with a sanitized key instead, as that way any plugin could use this meta in reports / queries more easily. Could consider adding a new key in addition to the existing one for backwards compat, deprecating the old one, ie `paypal_transaction_fee`

**Comment by DavidAnderson684** [comment]
Based on the description, isn't the root problem and thing to solve this part?

> WC_Admin_Report::get_order_report_data() can't use a meta key with a space in its name.

**Comment by mikejolley** [comment]
Whilst we log this data in meta, core has no use for it and has no plans on doing any reporting on it, or adding tools inside core to update/track it. In hindsight, it never should have been added to core.

Adding 2 meta keys for this data would be messy. So let's fix the report function.

**Comment by bekarice** [comment]
💥 that works too, thanks!
