### ISSUE TITLE
Update meta_data for product variation doesnt remove old meta objects REST API

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#16338]
**Description:**

meta_data for products and product variations is not correctly updated on PUT. (Removed value / key pairs is not beeing deleted)

PUT request to

/wp-json/wc/v2/products/511/variations/592

with data:

`{"meta_data":[{"id":14713,"key":"hfsgh","value":"fgshfs"}]}`

returns:

```
{"meta_data":[{"id":14713,"key":"hfsgh","value":"fgshfs"},
 {"id":1345,"key":"sfhh","value":"hfs"}]}
```

Expected id 1345 to be removed

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Only `meta_data` you provide is updated. It should not clear all undefined meta data too. If you want to clear existing `meta_data` values, pass a value of `null` for each item.
