### ISSUE TITLE
Order item meta is not displayed if meta value matches suffix of product name

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce#16656]
Originally reported by @conschneider in PAO repo. However, this is reproducible on a test site with only WooCommerce activated.

The reason order item meta is not displayed, both on admin order screen and front-end order summary, is:

https://github.com/woocommerce/woocommerce/blob/4101e313bb18c588d3e7dbd5170e6d19ad275b53/includes/class-wc-order-item.php#L268-L270

Especially `wc_is_attribute_in_product_name` function:

https://github.com/woocommerce/woocommerce/blob/38d9499c76bcb79e352c93f6ea0da0cdf383dcff/includes/wc-attribute-functions.php#L326-L337 

The comment says:

> Check if an attribute is included in the attributes area of a variation name.

which I assume this should only be used when product name to check is a variation, yes? In such case, maybe we could add additional check like:

```php
if ( ! $include_all && $product && $product->is_type( 'variation' ) && wc_is_attribute_in_product_name( $display_value, $order_item_name ) ) { 
 	continue; 
 } 
```

If that sounds right, I'm happy to send a PR.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create an order.
2. Add a simple virtual product with product title "simple virtual".
3. Add meta to that with key set to anything and value set to "virtual".

See recordings below:

![gif](https://cloudup.com/cwMQcw9voO3+)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
@gedex Sounds good. Please send a PR.

**Comment by Umangvaghela** [comment]
@gedex
 
Should I send the PR for this issue?

**Comment by conschneider** [comment]
Gracias á todos for the super quick solution. 🎉
