### ISSUE TITLE
PHP notice Trying to get property of non-object when reading product meta data

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce#17047]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

View shop page, single product page, or any page that reads product metadata.

You may need to have an extension that store custom metadata active (e.g, subscriptions or deposits).

## Expected/actual behavior

When I follow those steps, I see PHP notice is thrown:

```
Notice: Trying to get property of non-object in /srv/www/wordpress-default/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php on line 313
```

I was expecting to see no notice.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

Notice is not thrown in WC 3.1.2.

https://github.com/woocommerce/woocommerce/blob/0e40d2c764f2592fcd238b28c8ee52ff380ed0ce/includes/abstracts/abstract-wc-data.php#L285

It seems `$meta_data[ current( $array_keys ) ]` is always an array instead of an object. PR is coming.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17058
