### ISSUE TITLE
Custom checkout field loaded from Customer meta and then cleared by address-i18n.js

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#17353]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a custom checkout field, and set it to "hidden" for the "default" locale and show for a specific locale.
``` php
/**
 * Add custom checkout field
 */
add_filter( 'woocommerce_billing_fields', 'woocommerce_billing_fields_custom', 10, 2 );
function woocommerce_billing_fields_custom( $fields, $country ) {
	// Add Street name
	$fields['billing_custom'] = array(
		'label'			=> 'Custom',
		'placeholder'	=> 'Custom',
		'class'			=> array( 'form-row-wide' ),
		'required'		=> false
	);
	return $fields;
}
/**
 * Limit custom checkout field to NL
 */
add_filter( 'woocommerce_country_locale_field_selectors', 'woocommerce_country_locale_field_selectors' );
add_filter( 'woocommerce_default_address_fields', 'woocommerce_default_address_fields' );
add_filter( 'woocommerce_get_country_locale', 'woocommerce_get_country_locale' );

function woocommerce_country_locale_field_selectors( $locale_fields ) {
	$custom_locale_fields = array(
		'custom'  => '#billing_custom_field',
	);

	$locale_fields = array_merge( $locale_fields, $custom_locale_fields );

	return $locale_fields;
}

function woocommerce_default_address_fields( $fields ) {
	$custom_fields = array(
		'custom' => array(
			'hidden'	=> true,
			'required'	=> false,
		),
	);

	$fields = array_merge( $fields, $custom_fields );

	return $fields;
}

function woocommerce_get_country_locale( $locale ) {
	$locale['NL']['custom'] = array(
		'required'  => true,
		'hidden'	=> false,
	);

	return $locale;
}
``` 
2. When logged in, and going through the checkout (selecting Netherlands in this example), this data is automatically stored in the user meta (`billing_custom`).
3. When going through the checkout again, this field is initially populated with this data from the user meta (via `WC_Checkout::get_value()`).
4. Frontend AJAX scripts clear this value from the input field even when NL is selected (see comment here for details: https://github.com/woocommerce/woocommerce/pull/16870#commitcomment-25098711).

## Expected/actual behavior

When I follow those steps, the custom checkout field is loaded from the user profile and then cleared by address-i18n.js.

I was expecting to see this field properly populated as it used to be before 3.2.

I believe this bug was introduced with https://github.com/woocommerce/woocommerce/commit/eb3396328bc3417c40ad1f9e17649c82fa0f7662 in relation to #16868, #16870 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```

```
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17407
