### ISSUE TITLE
Wizard: changes to the Store Setup step

### ISSUE THREAD

**Issue by kellychoffman** [woocommerce/woocommerce#17427]
Feedback about the first page of the wizard from the user research lab at WooConf:

- [x] The location drop down was very confusing for people in the United States because it behaves differently than everything else in the list. You are able to select all countries but the US. Clicking on the country does nothing even though it looks like a selectable option. We should select the first state in the list so its clear that you can't select the country.
- [x] Currency was hard to find for every single country. We should take the location entered above and surface the most obvious choices.
- [x] Searching for currencies should be less strict (you should be able to type “US dollar” to find the correct currency and not be required to type “United States Dollar”).
- [x] People mentioned their stores use multi-currency, which is not supported by core. This tripped them up in the currency step when it only asks for one. Which one do they pick? We could add description text like "If your store supports multiple currency, choose one to start. You will be able to configure multiple currencies using an extension."

**Comment by pmaiorana** [comment]
A few related things that I think can also be improved:

1) We should detect/ask for their location and update the dropdown for them. The standard, in-browser "Do you want to share your location?" dialog is conventional and more straightforward to use than having to search in the dropdown.

2) When a user changes their location we should be "smart" and switch to that country's local currency for them.

3) When searching for "dollar" we should weight USD so it appears first, as it's going to be the most popular dollar.

**Comment by mikejolley** [comment]
cc @jeffstieler

**Comment by kellychoffman** [comment]
FYI: No design needed here, this is mostly code changes. Team X can review any PRs for interaction/usability.

**Comment by WPprodigy** [comment]
> Currency was hard to find for every single country. We should take the location entered above and surface the most obvious choices.

> When a user changes their location we should be "smart" and switch to that country's local currency for them.

1) Not sure when the change was made, but this appears to already be the case http://cld.wthms.co/CC3kdu
> People mentioned their stores use multi-currency, which is not supported by core.

2) I'd be hesitant to mention multi-currency at all, as core nor any of our plugins support it. Mentioning it during the setup process could be setting bad expectations. What about a simple text change instead that helps solve the confusion, like instead of "What currency do you use?", change it to "What is your store's main currency?"

> When searching for "dollar" we should weight USD so it appears first, as it's going to be the most popular dollar.

> Searching for currencies should be less strict (you should be able to type “US dollar” to find the correct currency and not be required to type “United States Dollar”).

3) Could maybe set up a custom matcher (https://select2.org/searching), but the easier solution here seems to be just moving US Dollar in `get_woocommerce_currencies()` to the top. It breaks alphabetical order, but that seems like a fine tradeoff if it's most often selected.

> The location drop down was very confusing for people in the United States because it behaves differently than everything else in the list.

> We should detect/ask for their location and update the dropdown for them.

4) Sounds like people were getting confused because they weren't used to option groups? Could create a conditional state field that appears for some countries, but that requires two selections/settings rather than just one. So not sure if it's worth the trade off.

Detecting the current user's location would be neat though for sure.


_____

Happy to help with these changes, just wanted to get some feedback first before continuing.

**Comment by mikejolley** [comment]
1 already happens indeed.

> I'd be hesitant to mention multi-currency at all, as core nor any of our plugins support it. 

Agreed. Update wording to state what currency you want to accept payments in?

> Searching for currencies should be less strict (you should be able to type “US dollar” to find the correct currency and not be required to type “United States Dollar”).





> The location drop down was very confusing for people in the United States because it behaves differently than everything else in the list. You are able to select all countries but the US. Clicking on the country does nothing even though it looks like a selectable option. We should select the first state in the list so its clear that you can't select the country.

Would need separate state field and JS. Or we can try adding better optgroup support to select2 for now.

> Currency was hard to find for every single country. We should take the location entered above and surface the most obvious choices.

Done if inside the locale setup files.

 > Searching for currencies should be less strict (you should be able to type “US dollar” to find the correct currency and not be required to type “United States Dollar”).
Need to customise the dropdown to add some aliases. Not sure if supported by select2 or not.


 People mentioned their stores use multi-currency, which is not supported by core. This tripped them up in the currency step when it only asks for one. Which one do they pick? We could add description text like "If your store supports multiple currency, choose one to start. You will be able to configure multiple currencies using an extension."


We should detect/ask for their location and update the dropdown for them. The standard, in-browser "Do you want to share your location?" dialog is conventional and more straightforward to use than having to search in the dropdown.

When a user changes their location we should be "smart" and switch to that country's local currency for them.

When searching for "dollar" we should weight USD so it appears first, as it's going to be the most popular dollar.

**Comment by kellychoffman** [comment]
> Update wording to state what currency you want to accept payments in?

I like this idea. If we mention anything about your store's "main"  currency, it sort of implies that you can have multiple.

**Comment by mikejolley** [comment]
See
