### ISSUE TITLE
Item Meta Escapes Quotes Wrongly

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#17607]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. On an order item add a new meta that contains a quote in it (ie. `Child's Name`).
2. Save the order
3. Keep Updating the order multiple times

## Expected/actual behavior

The item meta name should always be `Child's Name`.

When I follow those steps, I see the meta name being continuously escaped, and a `\` is added every time you updated.

![](http://d.wedj.at/wgjfw0+)
**Image Link**: http://d.wedj.at/wgjfw0+

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

Tested on WC 3.2.3

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17621
