### ISSUE TITLE
Missing order note meta (author and date) when added via AJAX

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce#17717]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. View edit screen of existing order.
2. Add new note with any text, type (private or to customer) doesn't matter.
3. Click **Add** button.

You'll get something like:

<img width="287" alt="screen shot 2017-11-16 at 12 53 06 am" src="https://user-images.githubusercontent.com/78313/32851790-8fdaa830-ca68-11e7-8956-4f43fd15ff96.png">

Now duplicate the current tab of the browser, you'll see how it differs:

<img width="289" alt="screen shot 2017-11-16 at 12 54 11 am" src="https://user-images.githubusercontent.com/78313/32851832-b3a80186-ca68-11e7-96f1-3b040c109ad1.png">

## Expected/actual behavior

When I follow those steps, I was expecting to see the other meta info: author and date. Unless this the expected design.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by gedex** [comment]
@mikejolley Happy to send a PR is this is an issue.

**Comment by mikejolley** [comment]
Thanks @gedex 

See https://github.com/woocommerce/woocommerce/pull/17718
