### ISSUE TITLE
Order item meta key and value

### ISSUE THREAD

**Issue by MarieComet** [woocommerce/woocommerce#17906]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Place and order with custom order item meta (like WooCommerce product add-ons plugin do)

## Expected/actual behavior

Actually order item meta keys are saved by default with the “human” readable value in `woocommerce_order_itemmeta` table.
It will be nice to add possibility for developpers to save order item meta as array in `woocommerce_checkout_create_order_line_item` and `add_meta_data` with `key`, `value`, `display_key` and `display_value` for later uses in code.
This is not a bug report issue, but an enhancement request (I think), or if I just don't understand how it works and my request is inappropriate please let me know how to do.
Thanks you.
`
## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
WordPress 4.9 with WooCommerce 3.2.5 and Twenty Seventeen.
```
</details>

**Comment by MarieComet** [comment]
Hi, since I published this issue I found the filter `woocommerce_order_item_display_meta_key` which allow me to edit the display key for my custom order item meta, it's an alternative that does the job for the moment.

**Comment by claudiosanches** [comment]
On database should be use readable values... Still it's possible use filters to handle exhibition like `woocommerce_order_item_display_meta_key` and `woocommerce_order_item_display_meta_value`.
