### ISSUE TITLE
Refund button is not showing up when tracking an order from woocommerce using shortcode [woocommerce_order_tracking]

### ISSUE THREAD

**Issue by Sidkt** [woocommerce/woocommerce#18648]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
woocommerce_order_tracking is for customer use. They cannot refund orders for themselves.

**Comment by Sidkt** [comment]
Hi mike, i am using YITH WooCommerce Advanced Refund System, Refund button is showing up on view order page, from where customer can fill a form and ask for refund, but its not showing up on order tracking page is there any way i can do that?

**Comment by mikejolley** [comment]
We're not affiliated with YITH. Ask them?

**Comment by Sidkt** [comment]
Thanks for guiding me, its fixed it was in Yith.
