### ISSUE TITLE
Usage tracking in setup wizard should be opt-in and include a link to the WooCommerce usage tracking page

### ISSUE THREAD

**Issue by mattradford** [woocommerce/woocommerce#19175]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Install and activate WooCommerce
2. Start setup wizard (/wp-admin/index.php?page=wc-setup)
3. View checkbox and text stating "Allow WooCommerce to collect non-sensitive diagnostic data and usage information.".

## Expected/actual behavior

When I follow those steps, I see the usage tracking checkbox is checked, and there is no link to the [page explaining what happens to your data](https://woocommerce.com/usage-tracking/).

I was expecting to see this checkbox unchecked and a link to the usage tracking page. Opt-in (not opt-out) and explaining what happens to data collected is required to be compliant with GDPR.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: http://testinstall.dev
Site URL: http://testinstall.dev
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1k

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.49 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 3.82MB
Database Data Size: 2.75MB
Database Index Size: 1.07MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.03MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 8
post: 2
revision: 7
um_directory: 1
um_form: 3
um_role: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Gravity Forms: by rocketgenius – 2.1.3
Date Field Conditional Logic for Gravity Forms: by Adrian Gordon – 1.0.0
Ultimate Member: by Ultimate Member – 1.3.81
Ultimate Member - HooYu: by Matt Radford at 10° – 1.0.0
WooCommerce: by Automattic – 3.3.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.2 – 1.4 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –


```
</details>

**Comment by mattradford** [comment]
How about this as an alternative? Larger text and a link to the Usage Tracking page.

![screen shot 2018-02-28 at 15 37 45](https://user-images.githubusercontent.com/2804540/36796420-71e88108-1c9d-11e8-9880-3bf9dea7221d.png)

**Comment by mikejolley** [comment]
Appearance wise I think we can take the checkbox styles and the 'newsletter' box type styling from other steps so it's not hidden. Obviously it would be good for this section to not go un-noticed because the data is useful for making decisions.

The wording above is much better. Linking is a good idea.

The tracking page is out of date and needs some edits:
- Looks like the coupon incentive is not longer in place/working so text needs removing.
- It needs to explain why admin email is collected, just so it's justified.
- It will (at some point) need instructions or a form to have that data removed on request.

**Comment by mattradford** [comment]
Something more like this?

![screen shot 2018-02-28 at 16 18 58](https://user-images.githubusercontent.com/2804540/36798674-2928490c-1ca3-11e8-8c54-a68050dce547.png)

**Comment by kellychoffman** [comment]
Thanks @mattradford. Thinking some additional text to describe the benefits will be really important here, especially for those who have no desire to read the usage tracking page. Thanks to @avivapinchas for the copy. 

![store setup - with opt-in messaging](https://user-images.githubusercontent.com/5835847/36821174-e115c264-1cae-11e8-91f4-811d3032c05e.jpg)

**Comment by mikejolley** [comment]
Thanks for the design feedback folks. Implementing shortly.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19206 It turns out we were not violating guidelines anyway, but we agree it should be unchecked by default. Will write up on the dev blog once live.
