### ISSUE TITLE
Use of woocommerce data store to hold meta outside of postmeta breaks admin filters

### ISSUE THREAD

**Issue by alexrowesoap** [woocommerce/woocommerce#19937]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [~] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a class that extends WC_Data_Store_WP and implements WC_Coupon_Data_Store_Interface, WC_Object_Data_Store_Interface
2. Use the class to store coupon meta in a different table
3. Confirm coupons still work on the frontend
4. Go into the coupon management page in the backend
5. Filter the list of coupons by coupon type

## Expected/actual behavior

Expected: The list table shows a list of coupons filtered by the selected type
Actual: No coupons are returned

What this seems to boil down to is woocommerce\includes\admin\list-tables\class-wc-admin-list-table-coupons.php not using the datastores for the query_filters. This may just be a case that WC_Admin_List_Table_Coupons needs extending alongside the new datastore, but this is not documented, and I cannot see where in said class this would be implemented.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: REDACTED
Site URL: REDACTED
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.1.8
PHP Version: 7.1.8
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_
Total Database Size: 4192.75MB
Database Data Size: 2461.74MB
Database Index Size: 1731.01MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 11.52MB + Index: 24.67MB
wp_woocommerce_order_items: Data: 27.56MB + Index: 17.58MB
wp_woocommerce_order_itemmeta: Data: 193.75MB + Index: 195.56MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
REDACTED
wp_commentmeta: Data: 0.44MB + Index: 0.33MB
wp_comments: Data: 6.52MB + Index: 1.30MB
wp_couponmeta: Data: 0.02MB + Index: 0.03MB
REDACTED
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.03MB
wp_followup_customers: Data: 1.52MB + Index: 1.31MB
wp_followup_customer_carts: Data: 64.52MB + Index: 1.78MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.52MB + Index: 0.36MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.39MB + Index: 0.13MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.06MB + Index: 0.05MB
wp_followup_order_categories: Data: 1.52MB + Index: 0.69MB
wp_followup_order_items: Data: 1.52MB + Index: 1.02MB
wp_followup_subscribers: Data: 0.16MB + Index: 0.20MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
REDACTED
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 9.52MB + Index: 2.52MB
wp_pmxe_exports: Data: 23.52MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Data: 21.55MB + Index: 0.00MB
wp_pmxe_templates: Data: 0.41MB + Index: 0.00MB
wp_pmxi_files: Data: 0.28MB + Index: 0.00MB
wp_pmxi_history: Data: 0.19MB + Index: 0.00MB
wp_pmxi_imports: Data: 59.52MB + Index: 0.00MB
wp_pmxi_posts: Data: 84.63MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.23MB + Index: 0.00MB
wp_postmeta: Data: 684.00MB + Index: 623.98MB
wp_posts: Data: 453.81MB + Index: 123.44MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 1.52MB + Index: 3.03MB
wp_term_relationships: Data: 3.52MB + Index: 3.52MB
wp_term_taxonomy: Data: 1.52MB + Index: 0.52MB
wp_usermeta: Data: 0.45MB + Index: 0.27MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_couponmeta: Data: 715.00MB + Index: 694.95MB
wp_woocommerce_worldpaycw_customer_contexts: Data: 1.52MB + Index: 1.52MB
wp_woocommerce_worldpaycw_documents: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_worldpaycw_ecc: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_worldpaycw_schema_version: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_worldpaycw_storage: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_worldpaycw_transactions: Data: 22.56MB + Index: 0.00MB
REDACTED
### Post Type Counts ###

attachment: 27913
REDACTED
page: 45
post: 135
product: 405
product_variation: 774
REDACTED
revision: 7
scheduled-action: 2
REDACTED
shop_coupon: 332297
shop_order: 83436
shop_order_refund: 21
shop_subscription: 74096
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

REDACTED
Advanced Custom Fields PRO: by Elliot Condon – 5.6.10
AffiliateWP - PayPal Payouts: by Pippin Williamson and Andrew Munro – 1.1.11
AffiliateWP - Recurring Referrals: by Pippin Williamson and Andrew Munro – 1.6.4
AffiliateWP: by AffiliateWP LLC – 2.1.17
AffiliateWP - Store Credit: by AffiliateWP LLC – 2.2.2
Better User Search: by Dale Higgs – 1.1.1
REDACTED
REDACTED
Contact Form 7: by Takayuki Miyoshi – 4.7
REDACTED
Google Captcha (reCAPTCHA) by BestWebSoft: by BestWebSoft – 1.36
REDACTED
REDACTED WooCommerce Custom Coupon Table: by REDACTED – 1.0.0 – Not tested with the active version of WooCommerce
REDACTED
WooCommerce Subscriptions Remove Deprecation Handlers: by Prospress Inc. – 1.0 – Not tested with the active version of WooCommerce
REDACTED
Woocommerce Bulk Attribute Manager: by Varun Sridharan – 2.2.1 – Not tested with the active version of WooCommerce
WooCommerce Currency Switcher: by realmag777 – 2.1.6 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.5.0
WooCommerce Kissmetrics: by WooThemes / SkyVerge – 1.8.0 – 1.11.1 is available – Not tested with the active version of WooCommerce
WooCommerce Product Bundles: by WooThemes – 5.0.2 – 5.7.8 is available – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.2.19
WooCommerce: by Automattic – 3.3.4 – 3.3.5 is available
REDACTED
WP All Export Pro: by Soflyy – 1.5.2
WP All Import Pro: by Soflyy – 4.5.1
REDACTED
WP All Import - ACF Add-On: by Soflyy – 3.1.6
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /shop/basket/
Checkout: #6 - /shop/checkout/
My account: #71 - /my-account/
Terms and conditions: #20719 - /terms-conditions/

### Theme ###

Name: REDACTED
Version: 1.0.5
Author URL: REDACTED
Child Theme: ❌ – REDACTED
WooCommerce Support: ✔

### Templates ###

Overrides: 
REDACTED/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/cart/cart-empty.php version - is out of date. The core version is 3.1.0
REDACTED/woocommerce/cart/cart-item-data.php
REDACTED/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.2.0
REDACTED/woocommerce/cart/cart-totals.php
REDACTED/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.3.0
REDACTED/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
REDACTED/woocommerce/cart/mini-cart.php version 2.5.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/cart/proceed-to-checkout-button.php
REDACTED/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 3.2.0
REDACTED/woocommerce/checkout/cart-errors.php
REDACTED/woocommerce/checkout/form-billing.php version 2.1.2 is out of date. The core version is 3.0.9
REDACTED/woocommerce/checkout/form-checkout.php version - is out of date. The core version is 2.3.0
REDACTED/woocommerce/checkout/form-coupon.php version 2.2 is out of date. The core version is 3.3.0
REDACTED/woocommerce/checkout/form-pay.php version 2.5.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/checkout/form-shipping.php version 2.2.0 is out of date. The core version is 3.0.9
REDACTED/woocommerce/checkout/payment-method.php
REDACTED/woocommerce/checkout/payment.php version 2.5.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/checkout/review-order.php version 2.3.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/checkout/terms.php version 2.5.0 is out of date. The core version is 3.1.1
REDACTED/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.2.0
REDACTED/woocommerce/content-product.php version 2.5.0 is out of date. The core version is 3.0.0
REDACTED/woocommerce/content-product_cat.php version 2.5.2 is out of date. The core version is 2.6.1
REDACTED/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
REDACTED/woocommerce/emails/admin-cancelled-order.php
REDACTED/woocommerce/emails/admin-failed-order.php
REDACTED/woocommerce/emails/admin-new-order.php
REDACTED/woocommerce/emails/customer-completed-order.php
REDACTED/woocommerce/emails/customer-invoice.php version 2.5.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/emails/customer-new-account.php
REDACTED/woocommerce/emails/customer-note.php
REDACTED/woocommerce/emails/customer-on-hold-order.php
REDACTED/woocommerce/emails/customer-processing-order.php
REDACTED/woocommerce/emails/customer-refunded-order.php
REDACTED/woocommerce/emails/customer-reset-password.php
REDACTED/woocommerce/emails/email-addresses.php version 2.4.0 is out of date. The core version is 3.2.1
REDACTED/woocommerce/emails/email-customer-details.php
REDACTED/woocommerce/emails/email-footer.php
REDACTED/woocommerce/emails/email-header.php
REDACTED/woocommerce/emails/email-order-details.php version 2.5.0 is out of date. The core version is 3.3.1
REDACTED/woocommerce/emails/email-order-items.php version 2.1.2 is out of date. The core version is 3.2.0
REDACTED/woocommerce/emails/email-styles.php version 2.3.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/emails/plain/admin-cancelled-order.php
REDACTED/woocommerce/emails/plain/admin-failed-order.php
REDACTED/woocommerce/emails/plain/admin-new-order.php
REDACTED/woocommerce/emails/plain/customer-completed-order.php
REDACTED/woocommerce/emails/plain/customer-invoice.php
REDACTED/woocommerce/emails/plain/customer-new-account.php
REDACTED/woocommerce/emails/plain/customer-note.php
REDACTED/woocommerce/emails/plain/customer-on-hold-order.php
REDACTED/woocommerce/emails/plain/customer-processing-order.php
REDACTED/woocommerce/emails/plain/customer-refunded-order.php
REDACTED/woocommerce/emails/plain/customer-reset-password.php
REDACTED/woocommerce/emails/plain/email-addresses.php version 2.2.0 is out of date. The core version is 3.2.1
REDACTED/woocommerce/emails/plain/email-customer-details.php
REDACTED/woocommerce/emails/plain/email-order-details.php version 2.5.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/emails/plain/email-order-items.php version 2.1.2 is out of date. The core version is 3.2.0
REDACTED/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/loop/loop-end.php
REDACTED/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/loop/no-products-found.php
REDACTED/woocommerce/loop/orderby.php version 2.2.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/loop/rating.php version 2.0.0 is out of date. The core version is 3.0.0
REDACTED/woocommerce/loop/sale-flash.php
REDACTED/woocommerce/myaccount/dashboard.php
REDACTED/woocommerce/myaccount/downloads.php version 2.6.0 is out of date. The core version is 3.2.0
REDACTED/woocommerce/myaccount/form-edit-account.php version 2.6.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/myaccount/form-edit-address.php version 2.6.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/myaccount/form-login.php version 2.2.6 is out of date. The core version is 3.3.0
REDACTED/woocommerce/myaccount/form-lost-password.php version 2.3.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/myaccount/form-reset-password.php version 2.6.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/myaccount/lost-password-confirmation.php
REDACTED/woocommerce/myaccount/my-account.php
REDACTED/woocommerce/myaccount/my-address.php
REDACTED/woocommerce/myaccount/my-orders.php
REDACTED/woocommerce/myaccount/navigation.php
REDACTED/woocommerce/myaccount/orders.php version 2.6.0 is out of date. The core version is 3.2.0
REDACTED/woocommerce/myaccount/view-order.php version 2.6.0 is out of date. The core version is 3.0.0
REDACTED/woocommerce/notices/error.php version 1.6.4 is out of date. The core version is 3.3.0
REDACTED/woocommerce/notices/notice.php
REDACTED/woocommerce/notices/success.php version 1.6.4 is out of date. The core version is 3.3.0
REDACTED/woocommerce/order/order-again.php
REDACTED/woocommerce/order/order-details-customer.php version 2.4.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/order/order-details-item.php version 2.5.0 is out of date. The core version is 3.0.0
REDACTED/woocommerce/order/order-details.php version 2.5.3 is out of date. The core version is 3.3.0
REDACTED/woocommerce/product-searchform.php version - is out of date. The core version is 3.3.0
REDACTED/woocommerce/single-product/add-to-cart/simple.php version - is out of date. The core version is 3.0.0
REDACTED/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
REDACTED/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
REDACTED/woocommerce/single-product/add-to-cart/variation.php
REDACTED/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 3.3.2
REDACTED/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update

### subscriptions ###

WCS_DEBUG: ❌
						Yes
Subscriptions Mode: ❌
						Staging
Subscriptions Template Theme Overrides: 
REDACTED/woocommerce/emails/customer-renewal-invoice.php version 1.4 is out of date. The core version is 1.4.0
REDACTED/woocommerce/emails/email-order-details.php 
REDACTED/woocommerce/emails/plain/email-order-details.php 
REDACTED/woocommerce/emails/plain/subscription-info.php version 1.5 is out of date. The core version is 1.5.0
REDACTED/woocommerce/emails/subscription-info.php version 1.5 is out of date. The core version is 1.5.0
REDACTED/woocommerce/myaccount/my-subscriptions.php 
REDACTED/woocommerce/myaccount/related-orders.php 
REDACTED/woocommerce/myaccount/related-subscriptions.php 
REDACTED/woocommerce/myaccount/view-subscription.php version 2.0 is out of date. The core version is 2.2.19					
					❌
					
						Learn how to update
Report Cache Enabled: ✔
						Yes
Cache Update Failures: ❌
						2 failure
`
```
</details>

**Comment by mikejolley** [comment]
Low priority for us right now; we still rely larger on WP Admin for coupon screens/listing coupons/filters. Since we don't see many performance issues with coupons, it would be better to continue focussing efforts around products/orders for now. 

If you want to give updating that list table for CRUD a shot please go ahead :)

**Comment by alexrowesoap** [comment]
Hi Mike,
Thanks for the info. Might be worth updating the docs on the data stores that this will also be a required step to do for people creating custom data stores.

**Comment by mikejolley** [comment]
@alexrowesoap I've made a note of this limitation in the docs https://github.com/woocommerce/woocommerce/wiki/Data-Stores#data-store-limitations-and-wp-admin

```
Currently, several WooCommerce screens still rely on WordPress to list objects. Examples of this include orders, coupons and products.

If you replace data via a data store some parts of the existing UI may fail. An example of this may be lists of coupons when using the type filter. This filter uses meta data, and is in turn passed to WordPress which runs a query using the WP_Query class. This cannot handle data outside of the regular meta tables (Ref #19937).

To get around this, usage of WP_Query would need to be deprecated and replaced with custom query classes and functions. This is something on on long term roadmap, as is replacing WP List Table screens with custom list tables powered by data stores. Contributions around this system are welcome, otherwise we'll be tackling it when we move away from the WordPress core List Table UI.
```

For now this isn't supported due to the limitations of the current UI. You could as a workaround, sync data between meta and your custom data store so backwards compatibility is maintained.

To fix this we'll need to move away from List Tables which is something that won't happen short term and something which needs design first, since we may as well kill 2 birds at the same time :) cc @claudiosanches @claudiulodro 

I'm closing this issue and we'll reopen either when we're ready to work on new list table screens in WP Admin, or if there is significant community interest to expedite this.

Thanks for putting it on our radar!
