### ISSUE TITLE
Order line item meta can't edit

### ISSUE THREAD

**Issue by jamsheerkrd** [woocommerce/woocommerce#21664]
Order products line meta fields can't be edited once it is added. Each time we try to edit, it will get saved as a new meta entry. This bug is related to issue https://github.com/woocommerce/woocommerce/issues/21640

**To Reproduce**
1. Go to 'orders in backend'
2. Click on 'open any of the order that made earlier, or you can create a test order now'
3. Scroll down to 'order items and click  the edit item'
4. Add a new meta item and save
5. Click edit again, and try to edit the meta name and value added in step 4
6. Instead of getting the name and value updated, it creates new entry 

**Screenshots**
Demonstration video https://www.useloom.com/share/18cf0c9454c44c418ffe023768242f5a 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
Home URL: |   | http://plugins.acodez.ca
-- | -- | --
Site URL: |   | http://plugins.acodez.ca
WooCommerce version: |   | 3.5.0
Log directory writable: |   | /home/jamsheer/Projects/plugins/wp/wp-content/uploads/wc-logs/
WordPress version: |   | 4.9.8
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   |  
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

```
</details>

**Comment by kloon** [comment]
Lets keep things in one issue #21640
