### ISSUE TITLE
Enabling Gutenberg editor disables product admin meta boxes

### ISSUE THREAD

**Issue by appideasDOTcom** [woocommerce/woocommerce#23673]
**Describe the bug**
When the Gutenberg editor is enabled for "products" post types, the administration of products loses some of its meta boxes. The two that I noticed are "Product tags" and "Product categories."

**To Reproduce**
1. Add a filter hook on 'use_block_editor_for_post_type' to return TRUE for post type "product"
2. Add or edit a product in wp-admin
3. Note that "Product tags" and "Product categories" meta boxes are not present.

**Expected behavior**
When switching from the classic editor to Gutenberg, I would expect for all meta boxes to be retained. That's the behavior we have experienced with all plugins and post types, including custom plugins and post types that we created and those we use from third parties. Extra code has not been needed to get meta boxes to appear in Gutenberg when they were working in the classic editor.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): http://wp.local
Site address (URL): http://wp.local
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.14 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.2.14
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.25
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 6.86MB
Database Data Size: 5.78MB
Database Index Size: 1.08MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_aidb_versions: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.52MB + Index: 0.02MB
wp_postmeta: Data: 0.20MB + Index: 0.09MB
wp_posts: Data: 3.52MB + Index: 0.13MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 183
boat-features: 22
boat-listings: 7
boat-models: 3
cpt-videos: 13
nav_menu_item: 20
page: 30
post: 3
product: 20
revision: 186
scheduled-action: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

HPI Common: by HPI/Pavati Developers – 1.0
WooCommerce: by Automattic – 3.6.2

### Inactive Plugins (9) ###

DigitalOcean Spaces Sync: by keeross – 2.0.5
Pavati Boat Features: by HPI/Pavati Developers – 1.0
Pavati Boat Listings: by HPI/Pavati Developers – 1.0
Pavati Boat Models: by HPI/Pavati Developers – 1.0
Pavati Custom Post Types: by HPI/Pavati Developers – 1.0
Post Types Order: by Nsp Code – 1.9.3.9
Theme Content Blocks: by Highway Products
Inc. – 1.0.0

WooCommerce Blocks: by Automattic – 2.0.1
YIKES Simple Taxonomy Ordering: by YIKES
Inc. – 2.0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #1501 - /shop/
Cart: #1502 - /cart/
Checkout: #1503 - /checkout/
My account: #1504 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Pavati Wake
Version: 1.0.0
Author URL: https://www.highwayproducts.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-05-08 10:00:01 -0700
Newest: 2019-05-08 10:00:01 -0700

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Workaround**
I can revert the editor back to classic by removing the use_block_editor_for_post_type filter hook, in which case, the missing inputs reappear. The particular inputs that I noticed are also available in the Quick Edit menu.

**Misc**
I imagine that the Gutenberg editor is disabled by default for a reason, but we need to be able to use Blocks with our site and shop, and it seems to work as expected with just a couple of things missing.

**Comment by claudiosanches** [comment]
Blocks are disabled on products by default because it's not supported yet. This will be updated or replaced in future versions.

**Comment by joshcoast** [comment]
It's been over a year now, still no Gutenberg?
