### ISSUE TITLE
Custom meta from theme not exporting with built-in product export

### ISSUE THREAD

**Issue by dimichatzi** [woocommerce/woocommerce#25187]
**Describe the bug**

Hi,

I am currently using the default WooCommerce CSV importer to upload my products on my shop but I have the following issue:

My current (premium) WP theme called WoodMart (https://themeforest.net/item/woodmart-woocommerce-wordpress-theme/20264492) supports by default ability to upload additional images for each variation in variable products. For this purpose theme stores additional variations images data as a post meta value for the PARENT product (not for each variation) and it is called "woodmart_variation_gallery_data" (https://gyazo.com/2cf77ad1fa1a8d85f7ef8e899f94af62).
It stores an array with IDs of variations and arrays with IDs of images for each variation. 

So after creating a sample variable product on my shop, I tried to export it in order to check the Custom Meta columns that it uses for the products. This way I would be able to understand how to upload via my own CSV additional images for each of my variations. (how to create the appropriate column on the CSV file). The strange thing is that the export CSV file contains all the Custom Meta columns of the theme like below (except the  "woodmart_variation_gallery_data" which is necessary for the additional images of variations, evef if I can see the additional images of variations normally on my front-end and on the back-end too):

Meta: woodmart_sguide_select
Meta: woodmart_total_stock_quantity
Meta: _product_360_image_gallery
Meta: _woodmart_main_layout
Meta: _woodmart_sidebar_width
Meta: _woodmart_custom_sidebar
Meta: _woodmart_product_design
Meta: _woodmart_single_product_style
Meta: _woodmart_thums_position
Meta: _woodmart_product-background
Meta: _woodmart_extra_content
Meta: _woodmart_extra_position
Meta: _woodmart_product_custom_tab_title
Meta: _woodmart_product_custom_tab_content
Meta: _woodmart_swatches_attribute
Meta: _woodmart_product_video
Meta: _woodmart_product_hashtag
Meta: _woodmart_new_label

**After talking with theme authors, they said to me that it seems to be a problem with the core export in WooCommerce. Is that possible you think?**

As a second test, I purchased the https://woocommerce.com/products/woocommerce-additional-variation-images/ plugin from official WooCommerce site which also does the same thing for variation images. So I followed the steps below;

1) I disabled my theme's feature for additional variation images.
2) I activated the woocommerce-additional-variation-images plugin
3) I used “Meta: _wc_additional_variation_images” column on my CSV (as per plugin's recommendation) in order to set via IDs the variation images of my variable products.
4) I uploaded the CSV and the images were uploaded normally. However the plugin makes a conflict with my current theme and variable product galleries are appeared like broken on my front-end.
5) However, I tried to export the sample products again on this case to check if the “Meta: _wc_additional_variation_images” column would be included in the export CSV file.
6) Indeed, the column was appeared as expected at the final export CSV.

So my question has to do with my current theme's Meta "woodmart_variation_gallery_data" and the reason of not exporting with built-in product export of WooCommerce. I want your opinion on this issue. Do you think that this issue is caused be theme or WooCommerce at last?

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.giftsontop.gr
Site address (URL): https://www.giftsontop.gr
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: el
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.33 - Συνιστούμε να χρησιμοποιήσετε την PHP έκδοση 7.2 ή παραπάνω για μεγαλύτερη απόδοση και ασφάλεια. Πως να ενημερώσετε την έκδοση της PHP σας
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp9m_
Συνολικό μέγεθος βάσης δεδομένων: 17.68MB
Μέγεθος βάσης δεδομένων: 15.85MB
Μέγεθος ευρετηρίου βάσης δεδομένων: 1.83MB
wp9m_woocommerce_sessions: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp9m_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9m_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9m_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp9m_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9m_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9m_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp9m_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9m_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9m_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9m_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9m_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9m_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9m_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9m_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9m_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp9m_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9m_options: Data: 2.03MB + Index: 0.08MB + Engine InnoDB
wp9m_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9m_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9m_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9m_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9m_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9m_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9m_postmeta: Data: 2.52MB + Index: 0.67MB + Engine InnoDB
wp9m_posts: Data: 10.48MB + Index: 0.20MB + Engine InnoDB
wp9m_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9m_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9m_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9m_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9m_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9m_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp9m_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp9m_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp9m_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9m_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp9m_woodmart_wishlists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp9m_woodmart_wishlist_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Akismet Anti-Spam: από τον/την Automattic – 4.1.3
AutoConvert Greeklish Permalinks: από τον/την Δημήτρης Μαυρουδής – 3.3.1 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
Classic Editor: από τον/την Συντελεστές WordPress – 1.5
Contact Form 7 - Dynamic Text Extension: από τον/την Chris Mavricos
SevenSpark – 2.0.3

Contact Form 7: από τον/την Takayuki Miyoshi – 5.1.6
WPBakery Page Builder: από τον/την Michael M - WPBakery.com – 6.0.5
Loco Translate: από τον/την Tim Whitlock – 2.3.1
MC4WP: Mailchimp for WordPress: από τον/την ibericode – 4.7.3
WooCommerce: από τον/την Automattic – 3.8.1
Woodmart Core: από τον/την  – 1.0.20

### Inactive Plugins (3) ###

SG Optimizer: από τον/την SiteGround – 5.3.7
Slider Revolution: από τον/την ThemePunch – 6.1.5
WooCommerce Additional Variation Images: από τον/την WooCommerce – 1.7.17

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Βάση καταστήματος: #58 - /shop/
Καλάθι: #59 - /cart/
Ταμείο: #60 - /checkout/
Ο λογαριασμός μου: #61 - /my-account/
Όροι και Προϋποθέσεις: #1342 - /ori-chrisis/

### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 4.3.0
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-product_cat.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product.php

### Action Scheduler ###

Complete: 1
Oldest: 2019-11-07 20:21:47 +0000
Newest: 2019-11-07 20:21:47 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by tammullen** [comment]
Thanks @dimichatzi for reporting this!

In this case it sounds like the exporter is working as expected.

I was able perform the same successful export as you did using the WooCommerce Additional Variation Images extension data.
I was also able to re-produce your issue that your theme variation image data wasn't exporting by inserting some meta data that looked like the screenshot you linked to.

I believe the reason why the meta data created by your theme isn't exporting is because the exporter doesn't export non-scalar meta data.
https://github.com/woocommerce/woocommerce/blob/master/includes/export/class-wc-product-csv-exporter.php#L711
It appears from the screenshot you provided the data created by your theme is non-scalar and therefore wouldn't be exported.

I think the best thing would be to check back with your theme authors again to confirm this assumption.

**Comment by juliaamosova** [comment]
@dimichatzi I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We'd be happy to take another look.

**Comment by Alnaggar94** [comment]
@dimichatzi @tammullen - I have the same problem could you please help me out?
