### ISSUE TITLE
WP 5.6 compatibility

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#27970]
Prepare WC for WP 5.6.

**Comment by peterfabian** [comment]
- [ ] review beta announcement
- [ ] check critical flows with the Beta
- [ ] check critical flows with the RC

**Comment by rodrigoprimo** [comment]
Closing as we finished all the testing that we were planning to do and WP 5.6 final was released.
