### ISSUE TITLE
Extend simple product api functionality

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#28886]
Extend simple product api functionality. 

### Tasks

- [x] [Redistribute properties between abstract and simple](https://github.com/woocommerce/woocommerce/issues/28985)
- [x] [Add External Product Type](https://github.com/woocommerce/woocommerce/issues/28885)
- [x] [Add Grouped Product Type](https://github.com/woocommerce/woocommerce/issues/28884)
- [x] [Add Variable Product Type](https://github.com/woocommerce/woocommerce/issues/28883)

**Comment by rrennick** [comment]
Closing as compete.
