### ISSUE TITLE
Implement variation filtering using lookup tables.

### ISSUE THREAD

**Issue by vedanshujain** [woocommerce/woocommerce#29611]
In #25524 we explored the possibility of variation filtering using lookup tables to solve multiple related issues -- #27935, #28368, #29242 etc. Given that a PoC was already done, it's time to start working on and implement the approach.

Implementing the approach will be a lot of effort. This issue will act as a placeholder for getting all the needed things done, and we will close this after the full approach including any DB migrations etc are implemented and merged to trunk. Meanwhile, we will open more issues to track the development of individual components:

- [ ] Extensive unit tests to spec the approach and prevent any future regressions. #29607
- [ ] Efficient migrations for creating and populating the DB table. #29608
- [ ] Implementing sync for the table whenever product changes. #29609 
- [ ] Implementing actually using the table for filtering, while also keeping older approach in use till the table is populated. #29610

**Comment by sukafia** [comment]
4053614-zen

**Comment by alexmoz2016** [comment]
I don't know if this is a known solution or not, but if you increase the maximum variations with ajax (**woocommerce_ajax_variation_threshold**), the multiple variations "out of stock" will disappear.
Maybe better explained here: https://wpza.net/unavailable-variations-wont-hide-in-woocommerce/
For example, if you have a product with "Size", "Color", "Shape" variations, each having multiple options (Size: 5, 6, 7, 8, 9; Color: red, green, yellow; Shape: square, round, triangle). Then if only sizes 5,8, with colors red and green, and Shapes Round and Square are in stock (so, 5-red-round is in stock, 8-green-triangle is not in stock). Changing that ajax entry to a higher number (I tried with 100), removes the non-stocked items from being diplayed on the product page.
If that ajax limit isn't changed, and if the "Hide non-stocked items" options is selected, ALL the possible combinations are still displayed, either in stock or not in stock.

**Comment by pacmanito** [comment]
@alexmoz2016 what you wrote is not related to the topic discussed here.

**Comment by peterfabian** [comment]
This has been fully rolled out in WC 6.3: https://href.li/?https://developer.woocommerce.com/2022/02/02/new-product-filtering-by-attributes-rolling-out-in-woocommerce-6-3/

Closing the epic.

**Comment by martincodecom** [comment]
Sorry if I’m asking this in the wrong place, (already asked it at the Woocommerce plugin support page, but the question was to complex/technical over there).

It is about filtering variable products that are in stock. Well explained in this article
[https://developer.woocommerce.com/2021/08/12/brace-yourselves-new-product-filtering-by-attributes-is-coming/](https://developer.woocommerce.com/2021/08/12/brace-yourselves-new-product-filtering-by-attributes-is-coming/)

Reading the issues/solutions here on github (this one and https://github.com/woocommerce/woocommerce/issues/25524) I’m wondering if there is a way now to query variable products, filtering for example on a specific Size (product attribute pa_size) and then only get the products returned with variations that are in stock.

It looks like it has been solved, reading the news post about WC 6.3 but I cannot find any info about the way to actually use this new solution in a WC_Product_Query or WP_Query. Is this already possible or is it only doable with wpdb queries?

To be more clear, an example query
```
$product_args = [
  'status' => 'publish',
  'limit' => $posts_per_page,
  'page' => $paged,
  'orderby' => 'date',
  'order' => 'DESC',
  
  // Filter on variation taxonomy size
  'tax_query' => array( array(
    'taxonomy' => 'pa_size',
    'field' => 'slug',
    'terms' => $sizes,
    'operator' => 'IN',
  ) ),
  
  // >>> In stock only, works for simple products only? Not working on variation level
  'stock_status' => 'instock',
];

$query = new WC_Product_Query( $product_args );
$products = $query->get_products();
```
