### ISSUE TITLE
api package version 0.3

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#29674]
This is the parent issue for features we need to add to the api package to provide full support to the rest api

- [ ] [Order refunds](https://github.com/woocommerce/woocommerce/issues/29292)
- [ ] [Order Notes](https://github.com/woocommerce/woocommerce/issues/31776)
- [ ] [Batch](https://github.com/woocommerce/woocommerce/issues/29570)
- [ ] [Customers](https://github.com/woocommerce/woocommerce/issues/31789)
- [ ] [Product categories & terms](https://github.com/woocommerce/woocommerce/issues/31790)
- [ ] [Product Tags & terms](https://github.com/woocommerce/woocommerce/issues/31792)
- [ ] [Product Attributes](https://github.com/woocommerce/woocommerce/issues/31793)
- [ ] [Product Attribute terms](https://github.com/woocommerce/woocommerce/issues/31794)
- [ ] [Product Reviews](https://github.com/woocommerce/woocommerce/issues/31796)
- [ ] [Shipping classes (global & product) ](https://github.com/woocommerce/woocommerce/issues/31801)
- [ ] [Tax rates](https://github.com/woocommerce/woocommerce/issues/31803)
- [ ] [Tax classes](https://github.com/woocommerce/woocommerce/issues/31802)
- [ ] [Webhooks](https://github.com/woocommerce/woocommerce/issues/31804)
- [ ] [Shipping Zones](https://github.com/woocommerce/woocommerce/issues/31805)
- [ ] [Shipping Zone Methods](https://github.com/woocommerce/woocommerce/issues/31806)
- [ ] [Shipping Zone Locations](https://github.com/woocommerce/woocommerce/issues/31808)
- [ ] [Shipping Methods](https://github.com/woocommerce/woocommerce/issues/31807)
