### ISSUE TITLE
[GlobalStep] For Atomic site, "Set up marketing tools" option in "Task List" fails to display on the "Woocommerce > Home" page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#31602]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

For Atomic site, "Set up marketing tools" option in "Task List" fails to display on the "Woocommerce > Home" page.

### Expected behavior

"Set up marketing tools" option in "Task List" is properly displayed on the "Woocommerce > Home" page.

### Actual behavior

"Set up marketing tools" option in "Task List" fails to display on the "Woocommerce > Home" page.

### Steps to reproduce

Steps To Reproduce:
1. Create any test site using Atomic site.
2. Install and activate all the required plugins
3. Complete the onboarding setup wizard.
4. Go to Woocommerce > Home page.
5. Observe that for Atomic site, "Set up marketing tools" option in "Task List" fails to display on the "Woocommerce > Home" page.
 

### WordPress Environment

WooCommerce: 6.1.0
Wordpress version: 5.8.3
PC:
Windows 10, Mac OS
Chrome(Version 97.0.4692.71) 
Firefox(Version 95.0.2)
Mac OS:
Safari: v15.1

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by joelclimbsthings** [comment]
It looks like this is a valid issue as I was able to reproduce in an Atomic Ephemeral site. After some digging, it seems to ultimately come down to [this function](https://github.com/woocommerce/woocommerce-admin/blob/1abef1a84da5c55bbffec7d37371896a7a7fe68d/src/Features/RemoteFreeExtensions/EvaluateExtension.php#L27) in `EvaluateExtension.php`. 

It's passing the `is_visible` property to the `evaluate()` function, which expects a set of rules. It should simply accept a boolean, and only evaluate if the property is not a boolean.
