### ISSUE TITLE
[Epic] Polish the out-of-the-box checkout experience

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce#45144]
A collection of bugs and improvements tickets applicable to the out-of-the-box experience in the following areas:
- Shopper experience
- WooCommerce Admin 
- Editor 

```[tasklist]
### Admin
- [ ] https://github.com/woocommerce/woocommerce/issues/41534
- [ ] https://github.com/woocommerce/woocommerce/issues/42287
- [ ] https://github.com/woocommerce/woocommerce/issues/42288
- [ ] https://github.com/woocommerce/woocommerce/issues/44120
- [ ] https://github.com/woocommerce/woocommerce/issues/46209
- [ ] https://github.com/woocommerce/woocommerce/issues/47734
```

```[tasklist]
### Shopper experience
- [ ] https://github.com/woocommerce/woocommerce/issues/44405
- [ ] https://github.com/woocommerce/woocommerce/issues/45160
- [ ] https://github.com/woocommerce/woocommerce/issues/42097
- [ ] https://github.com/woocommerce/woocommerce/issues/42430
- [ ] https://github.com/woocommerce/woocommerce/issues/42529
- [ ] https://github.com/woocommerce/woocommerce/issues/43500
- [ ] https://github.com/woocommerce/woocommerce/issues/42124
- [ ] https://github.com/woocommerce/woocommerce/issues/42422
- [ ] https://github.com/woocommerce/woocommerce/issues/42227
- [ ] https://github.com/woocommerce/woocommerce/issues/44906
- [ ] https://github.com/woocommerce/woocommerce/issues/30033
- [ ] https://github.com/woocommerce/woocommerce/issues/46263
- [ ] https://github.com/woocommerce/woocommerce/issues/46945
- [ ] https://github.com/woocommerce/woocommerce/issues/42111
- [ ] https://github.com/woocommerce/woocommerce/issues/45552
- [ ] https://github.com/woocommerce/woocommerce/issues/46179
- [ ] https://github.com/woocommerce/woocommerce/issues/46283
- [ ] https://github.com/woocommerce/woocommerce/issues/47557
- [ ] https://github.com/woocommerce/woocommerce/issues/47967
- [ ] https://github.com/woocommerce/woocommerce/issues/48088
- [ ] https://github.com/woocommerce/woocommerce/issues/48509
- [ ] https://github.com/woocommerce/woocommerce/issues/49558
- [ ] https://github.com/woocommerce/woocommerce/issues/51565
- [ ] https://github.com/woocommerce/woocommerce/issues/52335
- [ ] https://github.com/woocommerce/woocommerce/issues/48899
- [ ] https://github.com/woocommerce/woocommerce/issues/42022
```

```[tasklist]
### Editor
- [ ] https://github.com/woocommerce/woocommerce/issues/42091
- [ ] https://github.com/woocommerce/woocommerce/issues/42090
- [ ] https://github.com/woocommerce/woocommerce/issues/42099
- [ ] https://github.com/woocommerce/woocommerce/issues/42098
- [ ] https://github.com/woocommerce/woocommerce/issues/47175
- [ ] https://github.com/woocommerce/woocommerce/issues/46726
- [ ] https://github.com/woocommerce/woocommerce/issues/47029
- [ ] https://github.com/woocommerce/woocommerce/issues/47023
- [ ] https://github.com/woocommerce/woocommerce/issues/46166
- [ ] https://github.com/woocommerce/woocommerce/issues/48939
- [ ] https://github.com/woocommerce/woocommerce/issues/49481
- [ ] https://github.com/woocommerce/woocommerce/issues/52043
- [ ] https://github.com/woocommerce/woocommerce/issues/49095
- [ ] https://github.com/woocommerce/woocommerce/issues/54161
```

**Comment by pierorocca** [comment]
### Admin
- [ ] https://github.com/woocommerce/woocommerce/issues/41534
- [ ] https://github.com/woocommerce/woocommerce/issues/42287
- [ ] https://github.com/woocommerce/woocommerce/issues/42288
- [ ] https://github.com/woocommerce/woocommerce/issues/44120
- [ ] https://github.com/woocommerce/woocommerce/issues/46209
- [ ] https://github.com/woocommerce/woocommerce/issues/47734
### Shopper experience
- [ ] https://github.com/woocommerce/woocommerce/issues/44405
- [ ] https://github.com/woocommerce/woocommerce/issues/45160
- [ ] https://github.com/woocommerce/woocommerce/issues/42097
- [ ] https://github.com/woocommerce/woocommerce/issues/42430
- [ ] https://github.com/woocommerce/woocommerce/issues/42529
- [ ] https://github.com/woocommerce/woocommerce/issues/43500
- [ ] https://github.com/woocommerce/woocommerce/issues/42124
- [ ] https://github.com/woocommerce/woocommerce/issues/42422
- [ ] https://github.com/woocommerce/woocommerce/issues/42227
- [ ] https://github.com/woocommerce/woocommerce/issues/44906
- [ ] https://github.com/woocommerce/woocommerce/issues/30033
- [ ] https://github.com/woocommerce/woocommerce/issues/46263
- [ ] https://github.com/woocommerce/woocommerce/issues/46945
- [ ] https://github.com/woocommerce/woocommerce/issues/42111
- [ ] https://github.com/woocommerce/woocommerce/issues/45552
- [ ] https://github.com/woocommerce/woocommerce/issues/46179
- [ ] https://github.com/woocommerce/woocommerce/issues/46283
- [ ] https://github.com/woocommerce/woocommerce/issues/47557
- [ ] https://github.com/woocommerce/woocommerce/issues/47967
- [ ] https://github.com/woocommerce/woocommerce/issues/48088
- [ ] https://github.com/woocommerce/woocommerce/issues/48509
- [ ] https://github.com/woocommerce/woocommerce/issues/49558
- [ ] https://github.com/woocommerce/woocommerce/issues/51565
- [ ] https://github.com/woocommerce/woocommerce/issues/52335
- [ ] https://github.com/woocommerce/woocommerce/issues/48899
- [ ] https://github.com/woocommerce/woocommerce/issues/42022
### Editor
- [ ] https://github.com/woocommerce/woocommerce/issues/42091
- [ ] https://github.com/woocommerce/woocommerce/issues/42090
- [ ] https://github.com/woocommerce/woocommerce/issues/42099
- [ ] https://github.com/woocommerce/woocommerce/issues/42098
- [ ] https://github.com/woocommerce/woocommerce/issues/47175
- [ ] https://github.com/woocommerce/woocommerce/issues/46726
- [ ] https://github.com/woocommerce/woocommerce/issues/47029
- [ ] https://github.com/woocommerce/woocommerce/issues/47023
- [ ] https://github.com/woocommerce/woocommerce/issues/46166
- [ ] https://github.com/woocommerce/woocommerce/issues/48939
- [ ] https://github.com/woocommerce/woocommerce/issues/49481
- [ ] https://github.com/woocommerce/woocommerce/issues/52043
- [ ] https://github.com/woocommerce/woocommerce/issues/49095
- [ ] https://github.com/woocommerce/woocommerce/issues/54161

**Comment by ralucaStan** [comment]
Five of the 46 GitHub issues in the epic are still open. The epic has no Linear sub-issues. So I will be closing it.

**Still open**

* **Admin**: [#42287](<https://github.com/woocommerce/woocommerce/issues/42287>) Persist the checkout terms and conditions page in wp_options, like the privacy policy.
* **Admin**: [#42288](<https://github.com/woocommerce/woocommerce/issues/42288>) Persist a block-based site's privacy policy in wp_options, like shortcode sites do.
* **Shopper**: [#46179](<https://github.com/woocommerce/woocommerce/issues/46179>) Mini-cart placeholder styles are broken.
* **Editor**: [#42091](<https://github.com/woocommerce/woocommerce/issues/42091>) Cart and Checkout feedback prompt update, including CES.
* **Editor**: [#48939](<https://github.com/woocommerce/woocommerce/issues/48939>) Confusing experience when working on a draft Checkout block page.
