### ISSUE TITLE
[Epic] Select Control enhancements

### ISSUE THREAD

**Issue by mdperez86** [woocommerce/woocommerce#49040]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
There are some issues related to the SelectControl from Woo used in the new Product Editor.

```[tasklist]
### Select Control
- [ ] https://github.com/woocommerce/woocommerce/issues/35851 
- [ ] https://github.com/woocommerce/woocommerce/issues/35576
- [ ] https://github.com/woocommerce/woocommerce/issues/38231
- [ ] https://github.com/woocommerce/woocommerce/issues/38229
- [ ] https://github.com/woocommerce/woocommerce/issues/38218
- [ ] https://github.com/woocommerce/woocommerce/issues/38232
- [ ] https://github.com/woocommerce/woocommerce/issues/36283
```

**Comment by jamesckemp** [comment]
This version of the product editor is now deprecated
